[package]
name = "sample-map-generator"
version = "0.1.0"
authors = ["Aled Jones <aledjones.viola@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.3.9"
lazy_static = "1.4.0"
base64 = "0.13.0"
serde_json = "1.0"
csv = "1.1"
